Spectrum/Spectrum/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Spectrum.Model.Model;
using Spectrum.Bll.Bll;
using AutoMapper;
using Spectrum.Models;


namespace Spectrum.Controllers
{
    public class CategoryController : Controller
    {
        CategoryManager _categoryManager = new CategoryManager();
        [HttpGet]
        public ActionResult Add()
        {
            CategoryViewModel categoryViewModel = new CategoryViewModel();
            categoryViewModel.Categories = _categoryManager.GetAll();
            return View(categoryViewModel);

        }


        [HttpPost]
        public ActionResult Add(CategoryViewModel categoryViewModel)
        {
            string message = "";
            if (ModelState.IsValid)
            {
                Category category = Mapper.Map<Category>(categoryViewModel);
                if (_categoryManager.Add(category))
                {
                    message = "Category Added Successfully";
                }
                else
                {
                    message = "Not Saved";
                }
            }
            else
            {
                message = "ModelState Failed";
            }

            ViewBag.Message = message;
            categoryViewModel.Categories = _categoryManager.GetAll();
            return View(categoryViewModel);
        }

        [HttpGet]
        public ActionResult Search()
        {
            CategoryViewModel categoryViewModel = new CategoryViewModel();
            categoryViewModel.Categories = _categoryManager.GetAll();
            return View(categoryViewModel);
        }

        [HttpPost]
        public ActionResult Search(CategoryViewModel categoryViewModel)
        {
            var categories = _categoryManager.GetAll();
            if (categoryViewModel.Code != null)
            {
                categories = categories.Where(c => c.Code.Contains(categoryViewModel.Code)).ToList();
            }
            if (categoryViewModel.Name != null)
            {
                categories = categories.Where(c => c.Name.Contains(categoryViewModel.Name)).ToList();
            }

            categoryViewModel.Categories = categories;

            return View(categoryViewModel);
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {

            var category = _categoryManager.getById(id);
            CategoryViewModel categoryViewModel = Mapper.Map<CategoryViewModel>(category);
            categoryViewModel.Categories = _categoryManager.GetAll();

            return View(categoryViewModel);

        }
        // POST: Student/Edit/5	
        [HttpPost]
        public ActionResult Edit (CategoryViewModel categoryViewModel)
        {
            string message = "";


            if (ModelState.IsValid)
            {
                Category category = Mapper.Map<Category>(categoryViewModel);

                if (_categoryManager.Update(category))
                {
                    message = "Updated";
                }
                else
                {
                    message = "Not Updated";
                }
            }
            else
            {
                message = "Update Failed";
            }

            ViewBag.Message = message;
            categoryViewModel.Categories = _categoryManager.GetAll();
            return View(categoryViewModel);
        }
        //[HttpGet]
        //public ActionResult Edit(int id)
        //{
        //    var category = _categoryManager.getById(id);
        //    CategoryViewModel categoryViewModel = Mapper.Map<CategoryViewModel>(category);
        //    categoryViewModel.Categories = _categoryManager.GetAll();

        //    return View(categoryViewModel);

        //}
        //[HttpPost]
        //public ActionResult Edit(CategoryViewModel categoryViewModel)
        //{
        //    string message = "";
        //    if (ModelState.IsValid)
        //    {
        //        Category category = Mapper.Map<Category>(categoryViewModel);
        //        if (_categoryManager.Update(category))
        //        {
        //            message = "Updated!";
        //        }
        //        else
        //        {
        //            message = "Not Updated";
        //        }
        //    }
        //    else
        //    {
        //        message = "ModelState Failed";
        //    }

        //    ViewBag.Message = message;
        //    categoryViewModel.Categories = _categoryManager.GetAll();
        //    return View(categoryViewModel);
        //}


        [HttpGet]
        public ActionResult Delete(int id)
        {
            var category = _categoryManager.getById(id);
            CategoryViewModel categoryViewModel = Mapper.Map<CategoryViewModel>(category);
            categoryViewModel.Categories = _categoryManager.GetAll();

            return View(categoryViewModel);

        }
        [HttpPost]
        public ActionResult Delete(CategoryViewModel categoryViewModel)
        {
            string message = "";
            if (ModelState.IsValid)
            {
                Category category = Mapper.Map<Category>(categoryViewModel);
                if (_categoryManager.Delete(category.Id))
                {
                    message = "Deleted!!";
                }
                else
                {
                    message = "Not Deleted";
                }
            }
            else
            {
                message = "ModelState Failed";
            }

            ViewBag.Message = message;
            categoryViewModel.Categories = _categoryManager.GetAll();
            return View(categoryViewModel);
        }
    }
}

Spectrum/Spectrum/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Spectrum.Model.Model;
using Spectrum.Bll.Bll;
using Spectrum.Models;
using AutoMapper;
using Spectrum.DatabaseContext.DatabaseContext;


namespace Spectrum.Controllers
{
    public class ProductController : Controller
    {
        ProductManager _productManager = new ProductManager();
        CategoryManager _categoryManager = new CategoryManager();
        ProjectDbContext _dbContext = new ProjectDbContext();


        // GET: Product
        [HttpGet]
        public ActionResult Add()
        {
            ProductViewModel productViewModel = new ProductViewModel();
            productViewModel.Products = _productManager.GetAll();

            productViewModel.CategorySelectListItems = _categoryManager
                .GetAll().Select(c => new SelectListItem()
                {
                    Value = c.Id.ToString(),
                    Text = c.Name
                }).ToList();


            return View(productViewModel);
        }
        [HttpPost]
        public ActionResult Add(ProductViewModel productViewModel)
        {
            string message = "";


            if (ModelState.IsValid)
            {
                Product product = Mapper.Map<Product>(productViewModel);

                if (_productManager.Add(product))
                {
                    message = "Saved";
                }
                else
                {
                    message = "Not Saved";
                }
            }
            else
            {
                message = "Create Failed";
            }

            ViewBag.Message = message;
            productViewModel.Products = _productManager.GetAll();
            productViewModel.CategorySelectListItems = _categoryManager
                .GetAll()
                .Select(c => new SelectListItem()
                {
                    Value = c.Id.ToString(),
                    Text = c.Name
                }).ToList();
            return View(productViewModel);
        }
        public ActionResult ViewProduct(Product product)
        {
            ProductManager _productManager = new ProductManager();
            ModelState.Clear();
            return View(_productManager.GetAll());
        }




        [HttpGet]
        public ActionResult Update(int id)
        {

            var product = _productManager.getById(id);
            ProductViewModel productViewModel = Mapper.Map<ProductViewModel>(product);
            productViewModel.Products = _productManager.GetAll();

            productViewModel.CategorySelectListItems = _categoryManager
                .GetAll().Select(c => new SelectListItem()
                {
                    Value = c.Id.ToString(),
                    Text = c.Code
                }).ToList();

            return View(productViewModel);


        }
        // POST: Student/Edit/5	
        [HttpPost]
        public ActionResult Update(ProductViewModel productViewModel)
        {
            string message = "";


            if (ModelState.IsValid)
            {
                Product product = Mapper.Map<Product>(productViewModel);

                if (_productManager.Update(product))
                {
                    message = "Updated";
                }
                else
                {
                    message = "Not Updated";
                }
            }
            else
            {
                message = "Update Failed";
            }

            ViewBag.Message = message;
            productViewModel.Products = _productManager.GetAll();
            productViewModel.CategorySelectListItems = _categoryManager
                .GetAll().Select(c => new SelectListItem()
                {
                    Value = c.Id.ToString(),
                    Text = c.Code
                }).ToList();
            return View(productViewModel);
        }
        [HttpGet]
        public ActionResult Search(string searching)
        {
            var product = from s in _dbContext.Product
                          select s;
            if (!String.IsNullOrEmpty(searching))
            {
                product = product.Where(s => s.Code.Contains(searching) || s.Name.Contains(searching));
            }

            return View(product.ToList());
        }
        public ActionResult Delete(int id)
        {
            try
            {
                ProductManager productManager = new ProductManager();
                if (productManager.Delete(id))
                {
                    ViewBag.AlertMsg = "Deleted Successfully";
                }
                return RedirectToAction("ViewProduct");
            }
            catch
            {
                return View();
            }

        }
    }
}

Spectrum/Spectrum/Controllers/SalesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Spectrum.Model.Model;
using Spectrum.Bll.Bll;
using Spectrum.Models;
using AutoMapper;

namespace Spectrum.Controllers
{
    public class SalesController : Controller
    {
        CustomerManager _customerManager = new CustomerManager();
        CategoryManager _categoryManager = new CategoryManager();
        ProductManager _productManager = new ProductManager();
        PurchaseManager _purchaseManager = new PurchaseManager();
        SalesManager _salesManager = new SalesManager();

        [HttpGet]
        public ActionResult AddSales()
        {
            SalesViewModel salesViewModel = new SalesViewModel();
            salesViewModel.CustomerSelectListItems = _customerManager.GetAll().Select(c => new SelectListItem
            {
                Value = c.Id.ToString(),
                Text = c.Name
            }).ToList();



            salesViewModel.CategorySelectListItems = _categoryManager.GetAll().Select(c => new SelectListItem
            {
                Value = c.Id.ToString(),
                Text = c.Name
            }).ToList();

            ViewBag.Category = salesViewModel.CategorySelectListItems;
            ViewBag.SalesCode = 2019;
            ViewBag.emptyData = 0;
            return View(salesViewModel);
        }

        [HttpPost]
        public ActionResult AddSales(SalesViewModel salesViewModel)
        {
            salesViewModel.CustomerSelectListItems = _customerManager.GetAll().Select(c => new SelectListItem
            {
                Value = c.Id.ToString(),
                Text = c.Name
            }).ToList();

            ViewBag.Customer = salesViewModel.CustomerSelectListItems;



            salesViewModel.CategorySelectListItems = _categoryManager.GetAll().Select(c => new SelectListItem
            {
                Value = c.Id.ToString(),
                Text = c.Name
            }).ToList();


            var message = "";

            Sales sales = Mapper.Map<Sales>(salesViewModel);
            if (_salesManager.AddSales(sales))
            {
                ResetLoyaltyPoint(sales.CustomerId, sales.Id);
                message = "Sales Data Save Successfully!!";

            }
            else
            {
                message = "Not Save";
            }

            ViewBag.Category = salesViewModel.CategorySelectListItems;
            ViewBag.SalesCode = 2019;
            ViewBag.Message = message;

            return View(salesViewModel);
        }

        public void ResetLoyaltyPoint(int id, int SalesId)
        {
            var salesdetailsList = _salesManager.GetAllSalesDetails().Where(c => c.SalesId == SalesId).ToList();
            var grandtotal = ((from s in salesdetailsList select s.TotalMrp).Sum()) / 1000;

            var customer = _customerManager.GetById(id);
            var loyaltyPoint = customer.LoyaltyPoint / 10;

            customer.LoyaltyPoint += grandtotal - loyaltyPoint;
            _customerManager.UpdateLoyaltyPoint(customer);
        }
        public JsonResult GetProductByCategoryId(int categoryId)
        {
            var productList = _productManager.GetAll().Where(c => c.CategoryId == categoryId).ToList();
            var products = from p in productList select (new { p.Id, p.Name });
            return Json(products, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetLoyaltyPointByCustomerId(int customerId)
        {
            var customerList = _customerManager.GetAll().Where(c => c.Id == customerId).ToList();
            var loyaltyPoint = from c in customerList select (new { c.LoyaltyPoint, c.Name });
            return Json(loyaltyPoint, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetProductAvailableQuantityAndMrp(int productId)
        {

            var productList = _purchaseManager.GetAll().Where(c => c.ProductId == productId).ToList();
            var availavleQty = from p in productList select (new { p.Quantity, p.MRP });
            return Json(availavleQty, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetProductName(int productId)
        {
            var productList = _productManager.GetAll().Where(c => c.Id == productId).ToList();
            var productName = from p in productList select (p.Name);
            return Json(productName, JsonRequestBehavior.AllowGet);
        }
    }
}

Spectrum/Spectrum/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Specturm-small business Management syestem</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="~/Theme/vendors/iconfonts/mdi/css/materialdesignicons.css">
    <!-- endinject -->
    <!-- vendor css for this page -->
    <!-- End vendor css for this page -->
    <!-- inject:css -->
    <!-- inject:css -->
    <link rel="stylesheet" href="~/Theme/css/shared/style.css">
    <!-- endinject -->
    <!-- Layout style -->
    <link rel="stylesheet" href="~/Theme/css/demo_1/style.css">
    <!-- Layout style -->
    <link rel="shortcut icon" href="~/Theme/images/favicon.ico" />

    @RenderSection("Mystyle", false)

    <style>
        h2{
            color: red;
        }
    </style>

</head>
<body class="header-fixed">
    <!-- partial:partials/_header.html -->
@*<nav class="t-header">
        <div class="t-header-brand-wrapper">
            <a href="index.html">

               
              
            </a>
        </div>
        
    </nav>*@
<h2 align="center">Spectrum</h2>
<h2 align="center">Small Business Management System</h2>
    <!-- partial -->
    <div class="page-body">
        <!-- partial:partials/_sidebar.html -->
        <div class="sidebar">
            <div class="user-profile">
                
                    <p class="user-name"><b>Modules</b></p>

                
            </div>
            <ul class="navigation-menu">
                <li class="nav-category-divider"></li>

               

                <li>
                    <a href="#sample-pages" data-toggle="collapse" aria-expanded="false">
                        <span class="link-title">Module</span>
                        <i class="mdi mdi-flask link-icon"></i>
                    </a>
                    <ul class="collapse navigation-submenu" id="sample-pages">
                        <li>
                            <a href="@Url.Action("Add", "Category")">Category Module</a>

                            @*Rulls :: href = "@Url.Action("Edit", "ControllerName")*@

                        </li>
                        <li>
                            <a href="@Url.Action("Add", "Customer")">Customer Module</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Add", "Product")">Product Module</a>

                        </li>
                        <li>
                            <a href="@Url.Action("Add", "Supplier")">Supplier Module</a>
                        </li>
                    </ul>
                </li>

                <li>
                    <a href="@Url.Action("AddPurchase", "Purchase")">
                        <span class="link-title">Purchase Module</span>
                        <i class="mdi mdi-clipboard-outline link-icon"></i>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("AddSales", "Sales")">
                        <span class="link-title">Sales Module</span>
                        <i class="mdi mdi-chart-donut link-icon"></i>
                    </a>
                </li>
                
            </ul>

        </div>
        <!-- partial -->
        <div class="page-content-wrapper">
            <div class="page-content-wrapper-inner">
                <div class="content-viewport">
                    @*<div class="row">
                            <div class="col-12 py-5">
                                <hr /><hr />

                            </div>
                        </div>*@
                    <div class="row">


                        @RenderBody()



                    </div>
                </div>
            </div>
            <!-- content viewport ends -->
            <!-- partial:partials/_footer.html -->
            <footer class="footer">
                <div class="row">
                    <div class="col-sm-6 text-center text-sm-right order-sm-1">
                        <ul class="text-gray">
                            @*<li><a href="#">Terms of use</a></li>
                            <li><a href="#">Privacy Policy</a></li>*@
                        </ul>
                    </div>
                    <div class="col-sm-6 text-center text-sm-left mt-3 mt-sm-0">
                        <small class="text-muted d-block">Copyright © 2019 <a href="http://www.uxcandy.co" target="_blank">Developed By Specturm</a>. </small>
                       
                    </div>
                </div>
            </footer>
            <!-- partial -->
        </div>
        <!-- page content ends -->
    </div>
    <!--page body ends -->
    <!-- SCRIPT LOADING START FORM HERE /////////////-->
    <!-- plugins:js -->
    <script src="~/Theme/vendors/js/core.js"></script>
    <!-- endinject -->
    <!-- Vendor Js For This Page Ends-->
    <script src="~/Theme/vendors/apexcharts/apexcharts.min.js"></script>
    <script src="~/Theme/vendors/chartjs/Chart.min.js"></script>
    <script src="~/Theme/js/charts/chartjs.addon.js"></script>
    <!-- Vendor Js For This Page Ends-->
    <!-- build:js -->
    <script src="~/Theme/js/template.js"></script>
    <script src="~/Theme/js/dashboard.js"></script>
    <!-- endbuild -->
    @RenderSection("MyScript", false)
</body>
</html>