Spectrum/Spectrum/Models/PurchaseViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Spectrum.Model.Model;
using System.ComponentModel.DataAnnotations;

namespace Spectrum.Models
{
    public class PurchaseViewModel
    {


        public int Id { set; get; }


        public DateTime Date { set; get; }
        public string InvoiceNo { set; get; }

        public string SupplierName { set; get; }
        public int SupplierId { set; get; }
        public Supplier Supplier { set; get; }

        //for create table 
        public List<Purchase> Purchases { set; get; }





        //-------------------------------


        public string Code { set; get; }
        public DateTime ManuFractureDateTime { set; get; }
        public DateTime ExpireDateTime { set; get; }
        public string Remarks { set; get; }
        public int Quantity { set; get; }
        public int UnitPrice { set; get; }
        public int TotalPrice { set; get; }
        public int MRP { set; get; }

        public int ProductId { set; get; }
        public Product Product { set; get; }
        public int PurchaseId { set; get; }
        public Purchase Purchase { set; get; }

        public List<PurchaseDetails> PurchaseDetailses { set; get; }
        //----------------------------------------
        public List<SelectListItem> SupplierSelectListItems { set; get; }
        public List<SelectListItem> ProductSelectListItems { set; get; }

        public int CategoryId { set; get; }
        public Category Category { set; get; }
        public List<SelectListItem> CategorySelectListItems { set; get; }


    }
}

Spectrum/Spectrum/Controllers/PurchaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using Spectrum.Models;
using Spectrum.Model.Model;
using Spectrum.Bll.Bll;

namespace Spectrum.Controllers
{
    public class PurchaseController : Controller
    {
        SupplierManager _supplierManager = new SupplierManager();
        CategoryManager _categoryManager = new CategoryManager();
        ProductManager _productManager = new ProductManager();
        PurchaseManager _purchaseManager = new PurchaseManager();

        [HttpGet]
        public ActionResult AddPurchase()
        {
            PurchaseViewModel purchaseViewModel = new PurchaseViewModel();
            purchaseViewModel.SupplierSelectListItems = _supplierManager.GetAll().Select(c => new SelectListItem
            {
                Value = c.Id.ToString(),
                Text = c.Name
            }).ToList();


            purchaseViewModel.CategorySelectListItems = _categoryManager.GetAll().Select(c => new SelectListItem
            {
                Value = c.Id.ToString(),
                Text = c.Name
            }).ToList();

            ViewBag.Category = purchaseViewModel.CategorySelectListItems;



            //purchaseViewModel.ProductSelectListItems = _productManager.GetAll().Select(c => new SelectListItem
            //                                                                        {
            //                                                                            Value = c.Id.ToString(),
            //                                                                            Text = c.Name
            //                                                                        }).ToList();

            //if(purchaseViewModel.ProductSelectListItems)


            return View(purchaseViewModel);
        }

        public JsonResult GetSupplierNameBySupplierId(int supplierId)
        {
            var supplierList = _supplierManager.GetAll().Where(c => c.Id == supplierId).ToList();
            var supplier = from s in supplierList select (s.Name);
            return Json(supplier, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetProductByCategoryId(int categoryId)
        {
            var productList = _productManager.GetAll().Where(c => c.CategoryId == categoryId).ToList();
            var products = from p in productList select (new { p.Id, p.Name });
            return Json(products, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetProductCodeByProductId(int productId)
        {
            var productList = _productManager.GetAll().Where(c => c.Id == productId).ToList();
            var productCode = from p in productList select (new { p.Code, p.Name });
            return Json(productCode, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetPreviousProductPurchaseInfoByCode(int productId)
        {
            var purchaseProductCodeList = _purchaseManager.GetAll().Where(c => c.ProductId == productId).ToList();
            var purchaseProductCode = from p in purchaseProductCodeList select (new { p.UnitPrice, p.MRP });
            return Json(purchaseProductCode, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetPurchaseAvailableQuantity(int productId)
        {
            var purchaseProductCodeList = _purchaseManager.GetAll().Where(c => c.ProductId == productId).ToList();
            var availableQuantity = (from p in purchaseProductCodeList select p.Quantity).Sum();
            return Json(availableQuantity, JsonRequestBehavior.AllowGet);
            //return availableQuantity;
        }

        [HttpPost]
        public ActionResult AddPurchase(PurchaseViewModel purchaseViewModel)
        {
            purchaseViewModel.SupplierSelectListItems = _supplierManager.GetAll().Select(c => new SelectListItem
            {
                Value = c.Id.ToString(),
                Text = c.Name
            }).ToList();


            purchaseViewModel.CategorySelectListItems = _categoryManager.GetAll().Select(c => new SelectListItem
            {
                Value = c.Id.ToString(),
                Text = c.Name
            }).ToList();

            ViewBag.Category = purchaseViewModel.CategorySelectListItems;

            //purchaseViewModel.ProductSelectListItems = _productManager.GetAll().Select(c => new SelectListItem
            //                                                                        {
            //                                                                            Value = c.Id.ToString(),
            //                                                                            Text = c.Name
            //                                                                        }).ToList();




            string message = "";
            Purchase purchase = Mapper.Map<Purchase>(purchaseViewModel);
            if (_purchaseManager.Add(purchase))
            {
                message = "Data Save Successfully";
            }
            else
            {
                message = "not save";
            }

            ViewBag.Message = message;

            purchaseViewModel.Purchases = _purchaseManager.GetPurchaseReportAll();

            return View(purchaseViewModel);
        }

        [HttpGet]
        public ActionResult PurchaseInfo()
        {
            PurchaseViewModel purchaseViewModel = new PurchaseViewModel();
            purchaseViewModel.Purchases = _purchaseManager.GetPurchaseReportAll();
            return View(purchaseViewModel);
        }
        [HttpPost]
        public ActionResult PurchaseInfo(PurchaseViewModel purchaseViewModel)
        {
            //PurchaseViewModel purchaseViewModel = new PurchaseViewModel();
            purchaseViewModel.Purchases = _purchaseManager.GetPurchaseReportAll();
            return View(purchaseViewModel);
        }

        [HttpGet]
        public ActionResult PurchaseDetails(int Id)
        {
            PurchaseViewModel purchaseViewModel = new PurchaseViewModel();
            purchaseViewModel.PurchaseDetailses = _purchaseManager.GetAll().Where(c => c.PurchaseId == Id).ToList();
            return View(purchaseViewModel);
        }
        [HttpPost]
        public ActionResult PurchaseDetails(PurchaseViewModel purchaseViewModel)
        {
            purchaseViewModel.PurchaseDetailses = _purchaseManager.GetAll();
            return View(purchaseViewModel);
        }
        ////public ActionResult GetPurchaseDetailsByPurchaseId(int purchaseId)
        ////{
        ////    PurchaseViewModel purchaseViewModel = new PurchaseViewModel();
        ////    purchaseViewModel.PurchaseDetailses = _purchaseManager.GetAll().Where(c => c.PurchaseId == purchaseId).ToList();
        ////    return PartialView("Purchase/_purchaseReport", purchaseViewModel);
        ////}
    }
}

Spectrum/Spectrum/Views/Purchase/Add.cshtml
 @model Spectrum.Models.PurchaseViewModel
 @{
     Layout = "~/Views/Shared/_Layout.cshtml";
 }

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/CSS/Business/Purchase.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <meta name="viewport" content="width=device-width" />
    <title>Add</title>
</head>
<body>
    <div>



        <center>
            <h2>Purchase</h2>
        </center>
        <div class="div">
            <form method="post">
               
                <div class="table1">
                    <h5 style="margin-top:-24px; padding: 0px">Supplier Details</h5>
                    <table class="td">
                        <tr>
                            <td>@Html.LabelFor(c => c.Date)</td>
                            <td>@Html.EditorFor(model => model.Date, new {htmlAttributes = new {@class = "form-control"}, @value = DateTime.Now, @readonly = "readonly"}) </td>
                            <td> @Html.ValidationMessageFor(model => model.Date, "", new {@class = "text-danger"}) </td>
                        </tr>
                        <tr>
                            <td>@Html.LabelFor(c => c.InvoiceNo)</td>
                            <td>@Html.TextBoxFor(c => c.InvoiceNo, Model.InvoiceNo, new {id = "Invoice", @placeholder = "Code"})</td>
                            <td>@Html.ValidationMessageFor(c => c.InvoiceNo)</td>
                        </tr>
                        <tr>
                            <td>Supplier Name : </td>
                            <td>@Html.DropDownListFor(c => c.SupplierId, Model.SupplierSelect, "--Select--")</td>
                            <td></td>
                        </tr>
                    </table>
                </div>
                <div class="div1">
                    <table class="td1">
                        <tr>
                            <td>Product Name : </td>
                            <td>@Html.DropDownListFor(c => c.ProductId, Model.ProductSelect, "--Select--")</td>
                            <td></td>
                        </tr>
                        <tr>

                            <td>@Html.LabelFor(c => c.ManufactureDate)</td>
                            <td>@Html.EditorFor(model => model.ManufactureDate, new {id = "ManufactureDate", htmlAttributes = new {@class = "form-control"}, @value = DateTime.Now, @readonly = "readonly"}) </td>
                            <td> @Html.ValidationMessageFor(model => model.ManufactureDate, "", new {@class = "text-danger"}) </td>
                        </tr>
                        <tr>

                            <td>@Html.LabelFor(c => c.ExpireDate)</td>
                            <td>@Html.EditorFor(model => model.ExpireDate, new {htmlAttributes = new {id = "ExpireDate", @class = "form-control"}, @value = DateTime.Now, @readonly = "readonly"}) </td>
                            <td> @Html.ValidationMessageFor(model => model.ExpireDate, "", new {@class = "text-danger"}) </td>
                        </tr>
                        <tr>
                            <td>@Html.LabelFor(c => c.Remarks)</td>
                            <td>@Html.TextBoxFor(c => c.Remarks, Model.Remarks, new {@placeholder = "Write Remarks Values"})</td>
                            <td>@Html.ValidationMessageFor(c => c.Remarks)</td>
                        </tr>
                    </table>
                </div>
                <div class="div2">
                    <table class="td1">
                        <tr>
                            <td>@Html.LabelFor(c => c.Quantity)</td>
                            <td><input type="number" name="Quantity" id="quantity" value="@Model.Quantity"/></td>
                            <td>@Html.ValidationMessageFor(c => c.Quantity)</td>
                        </tr>
                        <tr>
                            <td>@Html.LabelFor(c => c.UnitPrice)</td>
                            <td><input type="number" name="UnitPrice" id="Unit" value="@Model.UnitPrice"/></td>
                            <td>@Html.ValidationMessageFor(c => c.UnitPrice)</td>
                        </tr>
                        <tr>
                        <td>@Html.LabelFor(c => c.TotalPrice)</td>
                        <td><input type="number" name="TotalPrice" id="Total" value="@Model.TotalPrice"/></td>
                        <td>@Html.ValidationMessageFor(c => c.TotalPrice)</td>
                        <tr>
                            <td>@Html.LabelFor(c => c.PreviousUnit)</td>
                            <td><input type="number" name="PreviousUnit" value="@Model.PreviousUnit"/></td>
                            <td>@Html.ValidationMessageFor(c => c.PreviousUnit)</td>
                        </tr>
                        <tr>
                            <td>@Html.LabelFor(c => c.PreviousMRP)</td>
                            <td><input type="number" name="PreviousMRP" value="@Model.PreviousMRP"/></td>
                            <td>@Html.ValidationMessageFor(c => c.PreviousMRP)</td>
                        </tr>
                        <tr>
                            <td>@Html.LabelFor(c => c.MRP)</td>
                            <td><input type="number" name="MRP" id="MRP" value="@Model.MRP"/></td>
                            <td>@Html.ValidationMessageFor(c => c.MRP)</td>
                            <td><input class="btn-danger btn-xs" type="button" id="add" value="Add"/></td>

                        </tr>
                    </table>
                </div>
                <table class="div4">
                    <thead>
                    <tr style="color:red">
                        <td>Sl</td>
                        <td>InVoice</td>
                        <td>Manufactured Date</td>
                        <td>Expire Date</td>
                        <td>Quantity</td>
                        <td>Unit Price(Tk)</td>
                        <td>Total(Tk)</td>
                        <td>MRP (Tk)</td>
                        <td><input type="submit" value="Save"/></td>
                    </tr>
                    </thead>
                    <tbody id="ResultDetailsTable"></tbody>
                </table>
            </form>



        </div>




    </div>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

    <script>
        $(document).ready(function () {
            var quantity = 0;
            var Unit = 0;
            var index = 0;
            $("#quantity").keyup(function () {
                if (!isNullOrEmpty($("#quantity").val())) {
                    quantity = parseInt($("#quantity").val());
                }
                if (!isNullOrEmpty($("#Unit").val())) {
                    Unit = parseInt($("#Unit").val());
                }
                $("#Total").val(quantity * Unit);
                $("#MRP").val(((Unit * 25) / 100) + (quantity * Unit));
                //$("#MRP").val(quantity * Unit)+((mrp/100)*(quantity * Unit));
            });
            $("#Unit").keyup(function () {
                if (!isNullOrEmpty($("#quantity").val())) {
                    quantity = parseInt($("#quantity").val());
                }
                if (!isNullOrEmpty($("#Unit").val())) {
                    Unit = parseInt($("#Unit").val());
                }
                $("#Total").val(quantity * Unit);
                $("#MRP").val(((Unit * 25) / 100) + (quantity * Unit));
                // $("#MRP").val((quantity * Unit)+((mrp/100)*(quantity * Unit)));
            });
            function isNullOrEmpty(data) {
                if (data === undefined || data === "" || isNaN(data)) {
                    return true;
                }
                return false;
            }
        });
        $(document).ready(function () {
            var index = 0;
            $('#add').click(function () {
                var result = GetResultData();
                var resultRow = GerResultRow(result);
                $("#ResultDetailsTable").append(resultRow);
                index++;
            });
            function GetResultData() {
                var Invoice = $('#Invoice').val();
                var ManufactureDate = $('#ManufactureDate').val();
                var ExpireDate = $('#ExpireDate').val();
                var quantity = $('#quantity').val();
                var Unit = $('#Unit').val();
                var Total = $('#Total').val();
                var MRP = $('#MRP').val();
                return { Invoice: Invoice, ManufactureDate: ManufactureDate, ExpireDate, quantity: quantity, Unit: Unit, Total: Total, MRP: MRP }
            }
            var sl = index;
            function GerResultRow(result) {
                var Invoice = "<input type='hidden' name='ResultDetailses[" + index + "].Invoice' value='" + result.Invoice + "'></div>";
                var ManufactureDate = "<input type='hidden' name='ResultDetailses[" + index + "].ManufactureDate' value='" + result.ManufactureDate + "'></div>";
                var ExpireDate = "<input type='hidden' name='ResultDetailses[" + index + "].ExpireDate' value='" + result.ExpireDate + "'></div>";
                var quantity = "<input type='hidden' name='ResultDetailses[" + index + "].quantity' value='" + result.quantity + "'></div>";
                var Unit = "<input type='hidden' name='ResultDetailses[" + index + "].Unit' value='" + result.Unit + "'></div>";
                var Total = "<input type='hidden' name='ResultDetailses[" + index + "].Total' value='" + result.Total + "'></div>";
                var MRP = "<input type='hidden' name='ResultDetailses[" + index + "].MRP' value='" + result.MRP + "'></div>";
                var startTr = "<tr>";
                var slCell = "<td class='text-success'>" + (++sl) + "</td>";
                var Invoice = "<td class='text-success'>" + Invoice + result.Invoice + "</td>";
                var ManufactureDate = "<td class='text-success'>" + ManufactureDate + result.ManufactureDate + "</td>";
                var ExpireDate = "<td class='text-success'>" + ExpireDate + result.ExpireDate + "</td>";
                var quantity = "<td class='text-success'>" + quantity + result.quantity + "</td>";
                var Unit = "<td class='text-success'>" + Unit + result.Unit + "</td>";
                var Total = "<td class='text-success'>" + Total + result.Total + "</td>";
                var MRP = "<td class='text-success'>" + MRP + result.MRP + "</td>";
                var endTr = "</tr>";
                return (startTr + slCell + Invoice + ManufactureDate + ExpireDate + quantity + Unit + Total + MRP + endTr);
            }
        });
    </script>
</body>
</html>

Spectrum/Spectrum/Views/Purchase/PurchaseDetails.cshtml
@model Spectrum.Models.PurchaseViewModel
@{
    /**/

    Layout = "~/Views/Shared/_Layout.cshtml";

}

<div class="card">
    <div class="grid-header">
        <div class="row">
            <label class="col-md-10">Purchase Report</label>

        </div>

    </div>

    <div class="card-body">
        <table class="table table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>SL</th>
                    <th>Code</th>
                    <th>ManufractureDate</th>
                    <th>ExpireDate</th>
                    <th>Quantity</th>
                    <th>Unit Price</th>
                    <th>MRP</th>
                    <th>TotalMrp</th>

                </tr>
            </thead>
            <tbody>
                @{ int i = 1;}
                @foreach (var purchase in Model.PurchaseDetailses)
                {
                    <tr>
                        <td>@(i++)</td>
                        <td>@purchase.Code</td>
                        <td>@purchase.ManuFractureDateTime</td>
                        <td>@purchase.ExpireDateTime</td>
                        <td>@purchase.Quantity</td>
                        <td>@purchase.UnitPrice</td>
                        <td>@purchase.MRP</td>
                        <td>@purchase.TotalPrice</td>



                    </tr>
                }


            </tbody>
        </table>
    </div>

</div>

Spectrum/Spectrum/Views/Purchase/PurchaseInfo.cshtml
@model Spectrum.Models.PurchaseViewModel
@{

    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container">

    <div class="card">
        <div class="grid-header">
            <div class="row">
                <label class="col-md-10">Purchase Report</label>

            </div>

        </div>

        <div class="card-body">
            <table class="table table-bordered">
                <thead class="thead-dark">
                    <tr>
                        <th>SL</th>
                        <th>Supplier Name</th>
                        <th>Invoice Number</th>
                        <th>Date</th>
                        <th>Details</th>

                    </tr>
                </thead>
                <tbody>
                    @{ int i = 1;}
                    @foreach (var purchase in Model.Purchases)
                    {
                        <tr>
                            <td>@(i++)</td>
                            <td>@purchase.SupplierName</td>
                            <td>@purchase.InvoiceNo</td>
                            <td>@purchase.Date</td>



                            <td>
                                @Html.ActionLink("Detalis", "PurchaseDetails", "Purchase", new { Id = purchase.Id }, null)

                                @*<a href="~/Views/Shared/Purchase/_purchaseReport.cshtml" id="partial"> Details</a>*@


                            </td>
                            <td style='visibility:hidden' id="purchaseId">@purchase.Id</td>
                        </tr>
                    }


                </tbody>
            </table>
        </div>
        <div class="row">
            @*<div class="col-md-12" id="studentPartial"></div>*@
            @*<a href="~/Views/Shared/Student/_StudentDetails.cshtml"id="partial"> </a>*@
        </div>

    </div>

    @*@{
            Html.RenderPartial("~/Views/Shared/Purchase/_purchaseReport.cshtml", Model);
        }*@
</div>

@*<script type="text/javascript">
        $(document).ready(function () {
            $("#partial").click(function () {
            var purchaseId = $("#purchaseId").val();
            var jsonrequestData = { PurchaseId: purchaseId };
            $.ajax({
                url: "/Purchase/GetPurchaseDetailsByPurchaseId",
                type: "POST",
                data: jsonrequestData,
                success: function (data) {

                    $("#partial").html(data);
                },
                error: function () {
                    alert("not done");
                }
            });
        });
    });
    </script>*@